# Exported from:        http://ip-172-31-23-1.ap-south-1.compute.internal:5516/
# Release version:      23.1.0-331.113
# Date created:         Thu Apr 06 08:56:13 UTC 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Application Security
spec:
- template: App Security Developer Check (Android)
  scheduledStartDate: 2023-03-31T03:30:00Z
  phases:
  - phase: New Phase
    tasks:
    - name: App Security Github Actions Parser
      type: opa.ParseGithubActionsLog
      opaServer: opaserver
      applicationType: Android
      username: mykolasvolkus
      gitPAT: !value "opa_ParseGithubActionsLog_App_Security_Github_Actions_Parser_gitPAT"
      repositoryName: AndroidAppProtectionTest
      runId: "4561561254"
      variableMapping:
        pythonScript.gitPAT: "${githubpat}"
        pythonScript.jsonInput: "${opaOutPut}"
    - name: Evaluate Policy Check
      type: opa.EvaluatePolicy
      opaServer: opaserver
      jsonInputForEvaluation: "${opaOutPut}"
      policyName: AppProtectionJsonPolicy
      expectedOutput: "{\"result\":{\"allow\":true,\"deny\":[]}}"
    - name: Deploy The Application
      type: xlrelease.ScriptTask
      script: print("Deploying the application")
  variables:
  - type: xlrelease.StringVariable
    key: inputPolicyJson
    requiresValue: false
    showOnReleaseStart: false
  - type: xlrelease.StringVariable
    key: opaOutPut
    requiresValue: false
    showOnReleaseStart: false
  - type: xlrelease.PasswordStringVariable
    key: githubpat
    requiresValue: false
    showOnReleaseStart: false
    value: !value "xlrelease_PasswordStringVariable_githubpat_value"
  riskProfile: Default risk profile
- template: App Security Developer Check (Android) - Jenkins
  scheduledStartDate: 2023-03-31T03:30:00Z
  phases:
  - phase: New Phase
    tasks:
    - name: App security  Jenkins Parser
      type: opa.ParseJenkinsLog
      opaServer: opaserver
      applicationType: Android
      jenkinsServer: jenkinsserver
      apiToken: !value "opa_ParseJenkinsLog_App_security__Jenkins_Parser_apiToken"
      jobUrl: http://43.205.232.54:8080/job/freestyle/5/
      variableMapping:
        pythonScript.jsonInput: "${inputPolicyJson}"
    - name: Evaluate Policy Check
      type: opa.EvaluatePolicy
      opaServer: opaserver
      jsonInputForEvaluation: "${inputPolicyJson}"
      policyName: AppProtectionJsonPolicy
      expectedOutput: "{\"result\":{\"allow\":true,\"deny\":[]}}"
    - name: Deploy The Application
      type: xlrelease.ScriptTask
      script: print("Deploying the application")
  variables:
  - type: xlrelease.StringVariable
    key: inputPolicyJson
    requiresValue: false
    showOnReleaseStart: false
  - type: xlrelease.StringVariable
    key: opaOutPut
    requiresValue: false
    showOnReleaseStart: false
  - type: xlrelease.PasswordStringVariable
    key: githubpat
    requiresValue: false
    showOnReleaseStart: false
    value: !value "xlrelease_PasswordStringVariable_githubpat_value_0"
  riskProfile: Default risk profile
- template: App Security Developer Check (IOS)
  description: App Security Developer Check (IOS) for IOS applicaiton
  scheduledStartDate: 2023-03-31T03:30:00Z
  phases:
  - phase: New Phase
    tasks:
    - name: App Security Github Actions Parser
      type: opa.ParseGithubActionsLog
      opaServer: opaserver
      username: mykolasvolkus
      gitPAT: !value "opa_ParseGithubActionsLog_App_Security_Github_Actions_Parser_gitPAT_0"
      repositoryName: AndroidAppProtectionTest
      runId: "4561561233"
      variableMapping:
        pythonScript.gitPAT: "${githubpat}"
        pythonScript.jsonInput: "${opaOutPut}"
    - name: Evaluate Policy Check
      type: opa.EvaluatePolicy
      opaServer: opaserver
      jsonInputForEvaluation: "${opaOutPut}"
      policyName: IosAppProtectionJsonPolicy
      expectedOutput: "{\"result\":{\"allow\":true,\"deny\":[]}}"
    - name: Deploy The Application
      type: xlrelease.ScriptTask
      script: print("Deploying the application")
  variables:
  - type: xlrelease.StringVariable
    key: inputPolicyJson
    requiresValue: false
    showOnReleaseStart: false
  - type: xlrelease.StringVariable
    key: opaOutPut
    requiresValue: false
    showOnReleaseStart: false
  - type: xlrelease.PasswordStringVariable
    key: githubpat
    requiresValue: false
    showOnReleaseStart: false
    value: !value "xlrelease_PasswordStringVariable_githubpat_value_1"
  riskProfile: Default risk profile
- notifications:
  - notification: TASK_OVERDUE
    priority: High
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release is overdue.

      After the task is completed, please mark it as Completed in Release.
    roles:
    - Watcher
    - Release Admin
    - Task Owner
  - notification: TASK_FLAGGED
    priority: High
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The status of the **${task.title}** task in the **${release.title}** release was changed to **${task.flagStatus}** with the following comment:

      **${release.flagComment}**
    roles:
    - Watcher
    - Release Admin
    - Task Team
  - notification: AUDIT_REPORT_JOB_ABORTED
    priority: Normal
    subject: "[Release] Audit report was aborted"
    body: |-
      **Your audit report was aborted!**

       Please try to generate it again or contact your Release administrator for assistance.
  - notification: MANUAL_TASK_STARTED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release has started and is assigned to you or your team.

      After the task is completed, please mark it as Completed in Release.
    roles:
    - Watcher
    - Task Owner
  - notification: TASK_FAILED
    priority: High
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release has failed.

      Other tasks could still be in progress, but the release will stop after they complete.

      You can retry the task, reassign it to somebody else or abort the release.
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: USER_MENTIONED
    priority: Normal
    subject: "[Release] ${mentionedByFullName} mentioned you on ${release.title}:\
      \ ${task.title}"
    body: "**${mentionedByFullName}** mentioned you on the **${task.title}** task\
      \ in the **${release.title}** release:"
  - notification: COMMENT_ADDED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      **${comment.authorFullName}** commented on the **${task.title}** task in the **${release.title}** release:

      ${comment.text}
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: AUDIT_REPORT_JOB_FAILED
    priority: Normal
    subject: "[Release] Audit report has failed"
    body: |-
      **Your audit report has failed!**

       Please try to generate it again or contact your Release administrator for assistance.
  - notification: RELEASE_FAILED
    priority: High
    subject: "[Release] ${release.title}"
    body: |-
      The **${release.title}** release has failed due to a task failure.

      The release is now stopped.

      You can retry the failed task, reassign it to somebody else or abort the release.
    roles:
    - Release Admin
  - notification: TASK_DUE_SOON
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release is due in **${task.dueInHours}** hours and **${task.dueInMinutes}** minutes.

      After the task is completed, please mark it as Completed in Release.
    roles:
    - Watcher
    - Release Admin
    - Task Owner
  - notification: ACTIVE_TASK_UNASSIGNED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release is active but not assigned to anyone anymore.

      Please assign the task to a user or a team.
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: RELEASE_FAILING
    priority: High
    subject: "[Release] ${release.title}"
    body: |-
      The **${release.title}** release is failing due to a task failure.

      Other tasks may still be in progress, but the release will stop after they complete.

      You can retry the failed task, reassign it to somebody else or abort the release.
    roles:
    - Release Admin
  - notification: USER_TOKEN_ABOUT_TO_EXPIRE
    priority: Normal
    subject: "[Release] Your personal access token is about to expire"
    body: |-
      Your personal access token "'${token.tokenNote}'" will expire in about ${token.expirationDurationInHours} hours.

       If this token is still needed, visit [Access tokens](${url}#/personal-access-token) to generate an equivalent.
  - notification: RELEASE_FLAGGED
    priority: High
    subject: "[Release] ${release.title}"
    body: |-
      The status of the **${release.title}** release was changed to **${release.flagStatus}** with the following comment:

      **${release.flagComment}**
    roles:
    - Release Admin
  - notification: MANUAL_TASK_STARTED_WITHOUT_OWNER
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release has started, but it is not assigned.

      Please assign the task to a user or a team.
    roles:
    - Watcher
    - Release Admin
  - notification: RELEASE_COMPLETED
    priority: Normal
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release has been completed."
    roles:
    - Release Admin
  - notification: TASK_WAITING_FOR_INPUT
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release needs your input.

      Please enter the required information so the release can continue.
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: AUDIT_REPORT_JOB_COMPLETED
    priority: Normal
    subject: "[Release] Report '${report.reportName}' is ready"
    body: |-
      **Your audit report is complete!**

       '${report.reportName}' is ready for download.
  - notification: GENERIC_SYSTEM_NOTIFICATION
    priority: Normal
    subject: "${notification.subject}"
    body: "${notification.body}"
  - notification: RELEASE_STARTED
    priority: Normal
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release has been started."
    bulkSubject: "[Release] Multiple releases started"
    bulkBody: |-
      The following releases have been started:

      ${#releases}
      * [${title}](${url})
      ${/releases}
    roles:
    - Release Admin
  - notification: RELEASE_ABORTED
    priority: Normal
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release has been aborted."
    bulkSubject: "[Release] Multiple releases aborted"
    bulkBody: |-
      The following releases have been aborted:

      ${#releases}
      * [${title}](${url})
      ${/releases}
    roles:
    - Release Admin
  - notification: ACTIVE_TASK_ASSIGNED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: "The active task **${task.title}** in the **${release.title}** release is\
      \ now assigned to ${task.ownerFullName}."
    roles:
    - Watcher
    - Task Team
    - Task Owner
