# Exported from:        http://host.docker.internal:5516/
# Release version:      23.1.0-412.1104
# Date created:         Wed Apr 19 11:51:07 UTC 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: OPA Management
spec:
- name: opaserver
  type: opa.Server
  url: http://43.205.232.54:8181/
  authenticationMethod: None
